### ISSUE TITLE
Vercel Deployment Issue (schema ENOENT)

### ISSUE THREAD

**Issue by maxpinheiro** [sandboxnu/faculty-activity-tracker#35]
Our vercel deployments are currently crashing with an internal error after a user attempts to sign in. The [Vercel logs](https://vercel.com/sandboxneu/faculty-activity-tracker/logs?page=1&timeline=past30Minutes&startDate=1682182931268&endDate=1682184731268&selectedLogId=1682184685469920527095377732&selectedLogTimestamp=1682184685469&forceEndDate=1682184685559) show the following error: `ENOENT: no such file or directory, open '/var/task/.next/server/chunks/schema.prisma'`

**Comment by Suraj-Ram** [comment]
Created new Postgres db in Vercel (new feature yay!) and updated prod env variable to point to it.
Didn;t require pull request.
