### ISSUE TITLE
Design - Standardized Colors

### ISSUE THREAD

**Issue by maxpinheiro** [sandboxnu/faculty-activity-tracker#37]
There are some colors used in the wireframes that don't match any colors in the style guide. For example:

![Image](https://user-images.githubusercontent.com/57200118/233810022-38a3f090-2d10-4ebf-b7cc-2d93d4cc4cd9.png)

Task: update the style guide in the figma to include all of the colors used in the wireframes. And update all colors in the wireframes to match the guide.

Ideally, I think we can use Figma's [color style library](https://help.figma.com/hc/en-us/articles/360039820134-Manage-and-share-styles) to create a list of our colors. That way, the developers can tell what color to use because the color's name will be displayed. For example (the fill on the side reads "Red" rather than #CC0000):

![Image](https://user-images.githubusercontent.com/57200118/233808984-5531854f-98b6-41d7-982d-c0cc75b32e99.png)

**Comment by Suraj-Ram** [comment]
Done by Max in #50
