### ISSUE TITLE
Github PR Templates

### ISSUE THREAD

**Issue by maxpinheiro** [sandboxnu/faculty-activity-tracker#44]
Create a template for our pull requests. See [instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) on creating a template. 

Template should have:
- Description: description of the task and what is added/changed
- Issue Number: associated ticket number, if applicable. this is to make sure the issue gets linked to the PR (which triggers automatic issue-closing on merged PRs)
- Things you especially want reviewed
- Screenshots (if applicable)
- Checklist:
   - [ ] Ticket name in PR title
   - [ ] Move status to Code Review in Github Project (should be automatic)
   - [ ] Team added to reviewers

**Comment by Suraj-Ram** [comment]
done
